### ISSUE TITLE
CRAN warning

### ISSUE THREAD

**Issue by krlmlr** [rwinlib/libmariadbclient#1]
about unsigned long long: https://github.com/rwinlib/libmariadbclient/blob/614faabab5ddc1e2659f1a3d5b5f5687dac8b377/include/mariadb/mysql.h#L48

WinBuilder logs: https://win-builder.r-project.org/QrP2c81JO4T2/00check.log

@jeroen: What's the best way to work around? Or just submit to CRAN and hope for the best?

**Comment by jeroen** [comment]
Try adding `CXX_STD=CXX11` to `Makevars.win` to allow C++11 features such as long long.

**Comment by krlmlr** [comment]
Thanks, this worked. I forgot that C++11 works well on Windows.
