### ISSUE TITLE
Please update to 2.3.4

### ISSUE THREAD

**Issue by krlmlr** [rwinlib/libmariadbclient#2]
Currently this seems to be the best bet for RMariaDB and perhaps also for RPostgres. I'm seeing weird problems for >=3.0.0 (https://github.com/r-dbi/RMariaDB/issues/69), so it might be better to back off for a while. On the other hand, 2.3.4 contains CONC-281, which helps MariaDB. Thanks!

**Comment by jeroen** [comment]
OK done, see https://github.com/r-dbi/RMariaDB/pull/82
