### ISSUE TITLE
Update to 2.3.5?

### ISSUE THREAD

**Issue by krlmlr** [rwinlib/libmariadbclient#3]
Per https://github.com/r-dbi/RMariaDB/issues/69#issuecomment-358752829, it would be great to have libmariadbclient 2.3.5 in the upcoming release. I haven't merged the 2.3.4 update yet, but I'm planning to release very soon.

Can we set up AppVeyor so that the binaries are built automatically?

Thanks for supporting rwinlib!

**Comment by jeroen** [comment]
ok I will look into this.

**Comment by jeroen** [comment]
We now have a 2.3.7 and 3.1.11 release.
