### ISSUE TITLE
Dialog Plugin

### ISSUE THREAD

**Issue by liamgilbey** [rwinlib/libmariadbclient#4]
Hi,

I am trying to use `RMariaDB` from a Windows client to connect to a remote MariaDB instance that is configured to authenticate through Active Directory.

From a linux client this works as expected, I believe as this is because it is relying on the system installation of `libmariadbclient`.

However, from inside the Windows client I am getting the following error:
```r
Error: Failed to connect: Plugin dialog could not be loaded: The specified module could not be found
```

I've done a bit of digging and `dialog` is a MariaDB plugin required to perform the AD authentication. 
Would it be possible to provide a windows version of `libmariadbclient` that was able to properly utilise this plugin?

Thanks

**Comment by jeroen** [comment]
Can you try sending a PR to https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-libmariadbclient/PKGBUILD ?

Does it work on MacOS? Here is what we use on MacOS: https://github.com/autobrew/homebrew-core/blob/master/Formula/mariadb-connector-c.rb#L26-L35

**Comment by liamgilbey** [comment]
Sure, from the looks of it the flags such as `-DCLIENT_PLUGIN_DIALOG=STATIC` on the MacOS version seem to be including those during the compilation. I unfortunately don't have access to a Mac to try this out however.

I think adding the flags to https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-libmariadbclient/PKGBUILD#L67 should help to resolve that issue there.

However, `RMariaDB` has [Makevars.win](https://github.com/r-dbi/RMariaDB/blob/master/src/Makevars.win) that calls [winlibs.R](https://github.com/r-dbi/RMariaDB/blob/master/tools/winlibs.R) to download and compile a DLL from this repo:

```r
VERSION <- commandArgs(TRUE)
...
download.file(sprintf("https://github.com/rwinlib/libmariadbclient/archive/v%s.zip", VERSION), "lib.zip", quiet = TRUE)
```

Would using the approach from `rtools-packages` require a further modification to either Makevars.win or [configure.win](https://github.com/r-dbi/RMariaDB/blob/master/configure.win) in RMariaDB?

**Comment by jeroen** [comment]
Yes, once we have new binaires in rtools, we can publish them, and then we can update RMariaDB to use a newer version.

**Comment by liamgilbey** [comment]
Right, yeah that does sound like a better approach. The PR is there, my skillset is a little lacking to actually test linking that into a version of RMariaDB, but I believe that's the correct place to include the required plugins for compiling

**Comment by jeroen** [comment]
Fixed in https://github.com/rwinlib/libmariadbclient/commit/d2e27852d5a8c84ec0ef344ac7c08584eef1cc64 see also discussion upstream: https://github.com/r-windows/rtools-packages/pull/170#issuecomment-745502945

**Comment by jeroen** [comment]
Fixed via https://github.com/r-windows/rtools-packages/pull/170#issuecomment-745502945
